Create headline
pirc25/portafolio pull request #1
Opened 2023-02-16 03:59 UTC by pirc25

At this first milestones of my portafolio, I did:

- Added index.html
- Added style.css
- Created toolbar
- Created headline

2023-02-16 04:52 UTC, Shedrack-Sunday requested changes
Hi @pirc25     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯 

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Descriptive commit messages 
  
Required Changes ♻️

- [x] You did very well in this project 👏 . However, there are a few changes required.
- I noticed a few semantic issues based on use cases of tags, which I commented on
- Also, there are slight adjustments you need to make on the fonts and your project will be all good to go 👍 

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-16 04:52 UTC, Shedrack-Sunday commented on index.html
> +  </nav>
- [ ] For this section, kindly wrap in round a `header` tag. This is in line with best practices when sectioning your navigation basically 👍

2023-02-16 04:52 UTC, Shedrack-Sunday commented on index.html
> +    <p id="toolbar-name">Richard Burneo</p>
- [ ] For your logo here, make it an `a` tag to signify a link and not use a `p` tag. 
- This is for three reasons: convention, semantics, and user experience(UX).

2023-02-16 04:52 UTC, Shedrack-Sunday commented on index.html
> +    </div>
- [ ] For this section, kindly use a `ul` tag to group the social links,  an `li` tag per icon, and finally an `a` tag for the icons.
- Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-02-16 04:52 UTC, Shedrack-Sunday commented on css/style.css
> +  align-items: center;
- [ ] The margin-top on your logo and hamburger needs a little adjustment to match that of the figma design. Making this change will give your users a better experience with your web app.

## Your view:
![image](https://user-images.githubusercontent.com/50990925/219270387-8559f745-b20c-4839-8f6e-87965b03b104.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/219270554-df60e131-bf69-4dbb-88df-d43c704ba25f.png)

2023-02-16 04:52 UTC, Shedrack-Sunday commented on css/style.css
> +  font-family: 'crete round', sans-serif;
- [ ] Kindly review the fonts provided on the [Template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27&t=5eryAHFhbT9gK0l9-0) to match your current design with that on the figma design. Yours seems a little bit bold. the exact width was provided n the link I attached 👍 

## Your view:
![image](https://user-images.githubusercontent.com/50990925/219271155-01ddcbbd-1b77-4c4d-9a63-456413e548e1.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/219271211-2e3bcca2-44d4-479f-8735-9ba927d6eca9.png)

2023-02-17 16:43 UTC, christianbiring1 approved these changes
Hi @pirc25 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![nicee](https://user-images.githubusercontent.com/97100091/219712004-00b45b64-6cec-439d-a957-dc0e2d7c8ed6.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] All changes were implemented as required by the reviewer :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 16:44 UTC, merged